In [20]:
import pandas as pd

In [21]:
movie = pd.read_csv('IMDB Dataset.csv')

In [22]:
movie.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [23]:
movie['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [24]:
d = pd.DataFrame({'col': ['People Love AI','AI Love data','data Love Love','Love People People']})

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv = CountVectorizer()

# Count Vectorizer

In [27]:
d

,col
0,People Love AI
1,AI Love data
2,data Love Love
3,Love People People


In [28]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]])

In [29]:
cv.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

# N-Gram Vectorization

#### BI-Gram Vactorization

In [30]:
cv = CountVectorizer(ngram_range = (2,2))

In [31]:
cv.fit_transform(d['col']).toarray()

array([[0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1]])

In [32]:
cv.vocabulary_

{'people love': 6,
 'love ai': 2,
 'ai love': 0,
 'love data': 3,
 'data love': 1,
 'love love': 4,
 'love people': 5,
 'people people': 7}

#### UNI-Gram Vactorization

In [33]:
cv = CountVectorizer(ngram_range = (1,1))

In [34]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]])

#### TRI-Gram Vactorization

In [35]:
cv = CountVectorizer(ngram_range = (3,3))

In [36]:
cv.fit_transform(d['col']).toarray()

array([[0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

# TFIDF

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tf=TfidfVectorizer()

In [39]:
tf.fit_transform(d['col']).toarray()

array([[0.64043405, 0.        , 0.42389674, 0.64043405],
       [0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.        , 0.60276058, 0.7979221 , 0.        ],
       [0.        , 0.        , 0.31418628, 0.94936136]])

In [40]:
tf.get_feature_names_out()

array(['ai', 'data', 'love', 'people'], dtype=object)

In [41]:
tf.idf_

array([1.51082562, 1.51082562, 1.        , 1.51082562])